-- ============================================================
-- V1 — Baseline Schema
-- Creates all 7 tables for the Mitra fitness tracking API.
-- Written in ANSI SQL compatible with PostgreSQL 16+ and H2.
-- ============================================================

-- 1. Users (root table — no foreign keys)
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    password    VARCHAR(255) NOT NULL,
    birth_date  DATE         NOT NULL,
    gender      VARCHAR(10)  NOT NULL,
    height_cm   INTEGER      NOT NULL,
    role        VARCHAR(20)  NOT NULL DEFAULT 'USER'
);

-- 2. Exercises (root table — no foreign keys)
CREATE TABLE exercises (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255)   NOT NULL UNIQUE,
    muscle_group   VARCHAR(255)   NOT NULL,
    met_factor     NUMERIC(4, 1)  NOT NULL,
    tracking_type  VARCHAR(12)    NOT NULL
);

-- 3. Body Measurements (FK → users)
CREATE TABLE body_measurements (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT        NOT NULL,
    weight_kg            NUMERIC(5, 2) NOT NULL,
    body_fat_percentage  NUMERIC(4, 2),
    record_date          DATE          NOT NULL,
    CONSTRAINT fk_body_measurements_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 4. Workout Routines (FK → users)
CREATE TABLE workout_routines (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT       NOT NULL,
    name     VARCHAR(255) NOT NULL,
    CONSTRAINT fk_workout_routines_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 5. Routine Exercises (FK → workout_routines, exercises)
CREATE TABLE routine_exercises (
    id                  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_routine_id  BIGINT  NOT NULL,
    exercise_id         BIGINT  NOT NULL,
    target_sets         INTEGER NOT NULL,
    target_reps         INTEGER,
    CONSTRAINT fk_routine_exercises_routine  FOREIGN KEY (workout_routine_id) REFERENCES workout_routines (id),
    CONSTRAINT fk_routine_exercises_exercise FOREIGN KEY (exercise_id)        REFERENCES exercises (id)
);

-- 6. Workout Sessions (FK → users, workout_routines)
CREATE TABLE workout_sessions (
    id                  BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT    NOT NULL,
    workout_routine_id  BIGINT    NOT NULL,
    start_time          TIMESTAMP NOT NULL,
    end_time            TIMESTAMP,
    CONSTRAINT fk_workout_sessions_user    FOREIGN KEY (user_id)            REFERENCES users (id),
    CONSTRAINT fk_workout_sessions_routine FOREIGN KEY (workout_routine_id) REFERENCES workout_routines (id)
);

-- 7. Set Records (FK → workout_sessions, exercises)
CREATE TABLE set_records (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_session_id  BIGINT         NOT NULL,
    exercise_id         BIGINT         NOT NULL,
    weight_kg           NUMERIC(6, 2),
    reps                INTEGER,
    duration_seconds    INTEGER,
    CONSTRAINT fk_set_records_session  FOREIGN KEY (workout_session_id) REFERENCES workout_sessions (id),
    CONSTRAINT fk_set_records_exercise FOREIGN KEY (exercise_id)        REFERENCES exercises (id)
);
